project/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('users/<username>/', views.user, name='user'),
    path('projects/<int:id>/', views.project, name='project'),
    path('projects/like/<int:id>/', views.like, name='like'),
    path('projects/dislike/<int:id>/', views.dislike, name='dislike'),
    path('projects/add/', views.add, name='add'),
    path('projects/remove/<int:id>/', views.remove, name='remove'),
    path('projects/edit/<int:id>/', views.edit, name='edit'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=32)
    image = models.ImageField(upload_to='images/')
    description = models.TextField(default='')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Like(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    

project/main/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from .models import Project

class RegisterForm(UserCreationForm):

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'input', 
            'placeholder' : 'Enter username...', 
            'id' : 'username'
            },
    ))

    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class' : 'input', 
            'placeholder' : 'Enter password...', 
            'id' : 'password'
        }
    ))

    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class' : 'input', 
            'placeholder' : 'Repeat password...', 
            'id' : 'repeat-password'
        }
    ))


class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class' : 'input', 
            'placeholder' : 'Enter username...', 
            'id' : 'username'
            }
    ))

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class' : 'input', 
            'placeholder' : 'Enter password...', 
            'id' : 'password'
        }
    ))


class ProjectForm(ModelForm):

    class Meta:
        model = Project
        fields = ['title', 'image', 'description']
        

project/main/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import RegisterForm, LoginForm, ProjectForm
from .models import Project, Like

# Create your views here.

def home(request):
    if request.user.is_authenticated:
        projects = Project.objects.order_by('-created')
        posts = []
        for project in projects:
            try:
                project.like_set.get(user=request.user)
                posts.append(Post(project, True))
            except:
                posts.append(Post(project, False))
            
        return render(request, 'home.html', {'user' : request.user, 'posts' : posts})
    else:
        return redirect('main:login')

def register(request):
    if request.method == 'POST':
        form = RegisterForm(data=request.POST)
        if form.is_valid():
            user = form.save() 
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = auth.authenticate(username=username, password=raw_password)
            auth.login(request, user)
            return redirect('main:home')
    else:
        form = RegisterForm()

    return render(request, 'authentication/register.html', {'form' : form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            user = auth.authenticate(username=username, password=raw_password)
            if user is not None:
                auth.login(request, user)
                return redirect('main:home')
                
    else:
        form = LoginForm()

    return render(request, 'authentication/login.html', {'form' : form})

@login_required
def logout(request):
    auth.logout(request)
    return redirect('main:login')

@login_required
def project(request, id):
    if request.method == 'GET':
        project = Project.objects.get(id=id)
        if (project == None):
            raise Http404()

        post = None
        try:
            project.like_set.get(user=request.user)
            post = Post(project, True)
        except:
            post = Post(project, False)

    return render(request, 'project.html', {'post' : post})

@login_required
def like(request, id):
    project = Project.objects.get(id=id)
    try:
        project.like_set.get(user=request.user)
    except:
        newLike = Like(user=request.user, project=project)
        newLike.save()

    return redirect('main:project', id=id)

@login_required
def dislike(request, id):
    project = Project.objects.get(id=id)
    try:
        like = project.like_set.get(user=request.user)
        like.delete()
    except:
        pass

    return redirect('main:project', id=id)

def user(request, username):
    try:
        user = User.objects.get(username=username)
        projects = user.project_set.order_by('-created')
        posts = []
        for project in projects:
            try:
                project.like_set.get(user=request.user)
                posts.append(Post(project, True))
            except:
                posts.append(Post(project, False))

        return render(request, 'user.html', {'user' : request.user, 'profile' : user, 'posts' : posts, 'count' : len(posts)})
    except:
        raise Http404()

@login_required
def add(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            user = request.user
            title = form.cleaned_data.get('title')
            image = form.cleaned_data.get('image')
            description = form.cleaned_data.get('description')
            newProject = Project(user=user, title=title, image=image, description=description)
            newProject.save()
            return redirect('main:home')

    else:
        form = ProjectForm()

    return render(request, 'add.html', {'form' : form})
        

@login_required
def remove(request, id):
    if request.method == 'GET':
        try:
            project = Project.objects.get(id=id)
            project.delete()
        except:
            raise Http404()

        return redirect('main:home')

    raise Http404()

@login_required
def edit(request, id):
    try:
        project = Project.objects.get(id=id)
    except:
        raise Http404()

    if request.method == 'POST':
        form = ProjectForm(request.POST, request.FILES)
        form.image
        if form.is_valid():
            project.title = form.cleaned_data.get('title')
            project.image = form.cleaned_data.get('image')
            project.description = form.cleaned_data.get('description')
            project.save()
            return redirect('main:project', id=id)

        else:
            return render(request, 'edit.html', {'form' : form, 'project' : project})

    else:
        form = ProjectForm(instance=project)
        return render(request, 'edit.html', {'form' : form, 'project' : project})



class Post:
    def __init__(self, project, liked):
        self.project = project
        self.liked = liked

project/main/templates/add.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Project</title>

    
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/add.css' %}">
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</head>
<body>

    {% include 'header.html' with add=False %}

    <div class='content-container'>
        <form action="{% url 'main:add' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            {{ form.non_field_errors }}
            
            <label for="title">Title:</label>
            {{ form.title }}
            {{ form.title.errors }}
    
            <label for="image">Thumbnail:</label>
            {{ form.image }}
            {{ form.image.errors }}

            <label for="description">Description:</label>
            {{ form.description }}
            {{ form.description.errors }}
    
            <button type="submit">Add</button>
        </form>
    </div>
    
</body>
</html>

project/main/templates/authentication/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Untitled page :(
        {% endblock title %}
    </title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/authentication.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</head>
<body>

    <h1>&lt;Script&gt;</h1>

    <p>&lt;Basic coding network&gt;</p>

    <hr>

    <div class='content-container'>
        {% block content %}
            <p>Block content goes here.</p>
        {% endblock content %}
    </div>
    
</body>
</html>

project/main/templates/authentication/login.html
{% extends 'authentication/base.html' %}

{% block title%}
    Login
{% endblock %}

{% block content %}
    <form action="{% url 'main:login' %}" method="POST">
        {% csrf_token %}

        <p class="title">Login</p>
        
        {{ form.non_field_errors }}
        
        <div class="tile">
            <label for="username">Username:</label>
            {{ form.username }}
            {{ form.username.errors }}
        </div>

        <div class="tile">
            <label for="password">Password:</label>
            {{ form.password }}
            {{ form.password.errors }}
        </div>

        <button type="submit" class="btn btn-primary">Login</button>

        <a href="{% url 'main:register' %}">You don't have account? Register here!</a>
    </form>
{% endblock %}

project/main/templates/authentication/register.html
{% extends 'authentication/base.html' %}

{% block title%}
    Register
{% endblock %}

{% block content %}
    <form action="{% url 'main:register' %}" method="POST">
        {% csrf_token %}

        <p class="title">Register</p>

        <div class="tile">
            <label for="username">Username:</label>
            {{ form.username }}
            {{ form.username.errors }}
        </div>

        <div class="tile">
            <label for="password">Password:</label>
            {{ form.password1 }}
            {{ form.password1.errors }}
        </div>

        <div class="tile">
            <label for="repeat-password">Repeat password:</label>
            {{ form.password2 }}
            {{ form.password2.errors }}
        </div>

        <button type="submit" class="btn btn-primary">Register</button>

        <a href="{% url 'main:login' %}" >You already have account? Login here!</a>
    </form>
{% endblock %}

project/main/templates/edit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Project</title>

    
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/add.css' %}">
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</head>
<body>

    {% include 'header.html' with add=True %}

    <div class='content-container'>
        <form action="{% url 'main:edit' project.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            {{ form.non_field_errors }}
            
            <label for="title">Title:</label>
            {{ form.title }}
            {{ form.title.errors }}
    
            <label for="image">Thumbnail:</label>
            {{ form.image }}
            {{ form.image.errors }}

            <label for="description">Description:</label>
            {{ form.description }}
            {{ form.description.errors }}
    
            <button type="submit">Save</button>
        </form>
    </div>
    
</body>
</html>

project/main/templates/header.html
{% load static %}

<header>
    <div>
        <img src="{% static 'img/avatar-small.png' %}" alt="User Image">
        <a href="{% url 'main:user' user.username %}" class="username">{{ user.username }}</a>
    </div>
    <a href="{% url 'main:home' %}"><h1>&lt;Script&gt;</h1></a>
    <a href="{% url 'main:logout' %}">Log out</a> 
    
    {% if add %}
        <a href="{% url 'main:add' %}" class="add-button">
            <img src="{% static 'img/add.png' %}" alt="Add">
            <p>New Project</p>
        </a>
    {% endif %}
</header>

<style>
    header {
        position: fixed;
        top: 0;
        width: 100%;
        height: 10vh;
        z-index: 1000;
        box-shadow: 0 10px 10px gray;
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        padding: 1vh 5%;
        align-items: center;
        background-color: inherit;
    }
    
    header h1 {
        font-size: 40pt;
        font-weight: 100;
        text-decoration: underline;
        margin: 0;
        padding: 0;
    }


    header p {
        font-weight: 700;
        margin: 0;
        padding: 0;
    }

    a {
        text-decoration: none;
    }

    a:link {
        color: black;
    }

    a:visited {
        color: black;
    }

    .username {
        font-weight: 700;
        font-size: 16pt;
    }

    .add-button {
        position: fixed;
        top: 15vh;
        box-shadow: 0 0 30px gray;
        border-radius: 50px;
        display: flex;
        flex-direction: row;
        justify-content: space-between;
        align-items: center;
        padding: 10px;
    }

    .add-button p {
        font-size: 16pt;
        padding-left: 10px;
    }

    .add-button:hover {
        transform: scale(1.1);
        box-shadow: 0 0 20px 5px gray;
    }
</style>

project/main/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Script</title>

    
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</head>
<body>

    {% include 'header.html' with add=True %}

    <div class='content-container'>
        {% for post in posts %}
            {% include 'project_card.html' with user=user post=post %}
        {% endfor %}
    </div>
    
</body>
</html>

project/main/templates/project.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{ post.project.title }} by {{ post.project.user.username }}</title>

        
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/project.css' %}">
        
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    </head>
    <body>

        {% include 'header.html' with add=True %}

        {% if post.project.user == user %}
            <div class="owner">
                <a href="{% url 'main:edit' post.project.id %}" class="">
                    <img src="{% static 'img/edit.png' %}" alt="Edit" class="">
                    <p>Edit Project</p>
                </a>
                <a href="{% url 'main:remove' post.project.id %}" class="">
                    <img src="{% static 'img/delete.png' %}" alt="Delete" class="">
                    <p>Delete Project</p>
                </a>
            </div>
        {% endif %}

        <div class="content-container">
            <div class="project-title">
                <h1>{{ post.project.title }}</h1>
                <p>by</p>
                <a href="{% url 'main:user' post.project.user.username %}">{{ post.project.user.username }}</a>
            </div>
            <img src="{{ post.project.image.url }}" alt="Project Thumbnail" class="thumbnail">
            <div class="flex">
                {% if post.liked %}
                    <img src="{% static 'img/full-heart.png' %}" alt="Liked" class="">
                {% else %}
                    <img src="{% static 'img/empty-heart.png' %}" alt="Not Liked" class="">
                {% endif %}
                <p>{{ post.project.like_set.count }} likes</p>
            </div>
            <p class="description">{{ post.project.description }}</p>
            {% if post.liked %}
                <a href="{% url 'main:dislike' post.project.id %}" class="btn btn-primary">Dislike</a>
            {% else %}
                <a href="{% url 'main:like' post.project.id %}" class="btn btn-primary">Like</a>
            {% endif %}
        </div>
        
    </body>
</html>

project/main/templates/project_card.html
{% load static %}

{% block content %}
    <div class="card">
        <img src="{{ post.project.image.url }}" alt="Project Thumbnail" class="card-img-top">
        <div class="card-body">
            <h5 class="card-title">{{ post.project.title }} by {{ post.project.user.username }}</h5>
            {% if post.liked %}
                <img src="{% static 'img/full-heart.png' %}" alt="Liked" class="">
            {% else %}
                <img src="{% static 'img/empty-heart.png' %}" alt="Not Liked" class="">
            {% endif %}
            <p>{{ post.project.like_set.count }} likes</p>
            <p class="card-text">{{ post.project.description }}</p>
            <a href="{% url 'main:project' post.project.id %}" class="btn btn-primary">View project</a>
        </div>
    </div>

    <style>
        .card {
            padding-top: 1%;
        }

        .card:hover {
            box-shadow: 0 0 30px gray;
            transform: scale(1.1);
            z-index: 500;
        }

        .card-title {
            font-weight: 700;
        }
    </style>
{% endblock %}

project/main/templates/user.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{{ logged_user.username }}</title>

        
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/user.css' %}">
        
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    </head>
    <body>

        {% include 'header.html' with add=True %}

        <div class="content-container">
            <div class="user-header">
                <div>
                    <img src="{% static 'img/avatar.png' %}" alt="User Image">
                    <h1>{{ profile.username }}</h1>
                </div>
                <p>{{ count }} projects</p>
            </div>
            <div class="posts-container">
                {% for post in posts %}
                    {% include 'project_card.html' with post=post %}
                {% endfor %}
            </div>
        </div>
        
    </body>
</html>